@base_url = {{$dotenv URL}}/api
@url={{base_url}}/report

GET {{url}}

###

GET {{url}}?page=1&count=1

###

GET {{url}}/id/1

###

GET {{url}}/nik/64711092301923

###

GET {{url}}/nik/64711092301923?page=1&count=5

###

GET {{url}}/no-image

###

GET {{url}}/no-image/id/1

###

GET {{url}}/extend

###

GET {{url}}/extend?page=1&count=5

###

GET {{url}}/id/2/extend

###

GET {{url}}/nik/64711092301923/extend

###

GET {{url}}/nik/64711092301923/extend?page=1&count=5

###

# POST {{url}}
# Content-Type: application/json

# {
#     "trashBinId": 2,
#     "nik": "6471109230192341",
#     "name": "Budi",
#     "phoneNumber": "6281234567891",
#     "imageName": "Test 123",
#     "imageData": "",
#     "description": "Tempat sampah rusak"
# }

###

PUT {{url}}/1/status
Content-Type: application/json

{
    "userId": 1,
    "status": "notResponded"
}

###

DELETE {{url}}/1

###