GET http://localhost:3001/api/report

###

GET http://localhost:3001/api/report/id/1

###

GET http://localhost:3001/api/report/nik/64711092301923

###

GET http://localhost:3001/api/report/extend

###

GET http://localhost:3001/api/report/id/2/extend

###

GET http://localhost:3001/api/report/nik/64711092301923/extend

###

POST http://localhost:3001/api/report
Content-Type: application/json

{
    "trashBinId": 2,
    "nik": "64711092301923",
    "name": "Budi Santoso",
    "phoneNumber": "6281234567891",
    "imagePath": "imagepath1",
    "description": "Tempat sampah rusak"
}

###

PUT http://localhost:3001/api/report/1/status
Content-Type: application/json

{
    "status": "notResponded"
}

###

DELETE http://localhost:3001/api/report/1

###