@base_url = {{$dotenv URL}}/api
@url={{base_url}}/trash

GET {{url}}

###

GET {{url}}?page=1&count=5

###

GET {{url}}/id/1

###

GET {{url}}/extend

###

GET {{url}}/extend?page=1&count=5

###

GET {{url}}/id/1/extend

###

POST {{url}}
Content-Type: application/json

{
    "name": "Trash Bin 3",
    "latitude": 100.00,
    "longitude": 150.00,
    "description": "Description 3"
}

###

PUT {{url}}/2
Content-Type: application/json

{
    "name": "Trash Bin 345",
    "latitude": 103.45,
    "longitude": 153.45,
    "description": null
}

###

PUT {{url}}/1/open-count/increase

###

DELETE {{url}}/1

###