GET http://localhost:3001/api/user
Content-Type: application/json

###

GET http://localhost:3001/api/user/2
Content-Type: application/json

###

POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username": "Username 4",
    "password": "Password 4"
}

###

PUT http://localhost:3001/api/user/4
Content-Type: application/json

{
    "username": "Username 1234",
    "password": "Password 1234"
}

###

DELETE http://localhost:3001/api/user/4

###