GET http://localhost:3001/api/user
Content-Type: application/json

###

GET http://localhost:3001/api/user/2
Content-Type: application/json

###

POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username": "Username 3",
    "password": "Password 3"
}

###

PUT http://localhost:3001/api/user/3
Content-Type: application/json

{
    "username": "Username 123",
    "password": "Password 123"
}

###

DELETE http://localhost:3001/api/user/3

###