@base_url = {{$dotenv URL}}/api
@url={{base_url}}/user

GET {{url}}

###

GET {{url}}/id/1

###

GET {{url}}/username/operator1

###

POST {{url}}
Content-Type: application/json

{
    "name": "Operator 1",
    "username": "operator1",
    "password": "password1",
    "phoneNumber": "6281234567891",
    "role": "operator",
    "active" : true,
    "description": "Description 1"
}

###

PUT {{url}}/1
Content-Type: application/json

{
    "name": "Name 345",
    "username": "username_345",
    "phoneNumber": "628123456789345",
    "role": "operator",
    "description": null
}

###

PUT {{url}}/1/password
Content-Type: application/json

{
    "oldPassword": "password_3",
    "newPassword": "password_345",
    "confirmPassword": "password_345"
}

###

PUT {{url}}/1/active
Content-Type: application/json

{
    "active": false
}

###

DELETE {{url}}/1

###