@base_url = {{$dotenv URL}}/api
@url={{base_url}}/feedback

GET {{url}}

###

GET {{url}}/id/1

###

POST {{url}}
Content-Type: application/json

{
    "reportId": 1,
    "title": "First Response",
    "description": "First Description"
}

###

DELETE {{url}}/1

###