@base_url = {{$dotenv URL}}/api
@url={{base_url}}/sub-trash-bin

GET {{url}}

###

GET {{url}}/id/1

###

GET {{url}}/extend

###

GET {{url}}/id/1/extend

###

POST {{url}}
Content-Type: application/json

{
    "trashBinId": 21,
    "name": "Sub Trash Bin 3"
}

###

PUT {{url}}/1
Content-Type: application/json

{
    "name": "Sub Trash Bin 4"
}

###

DELETE {{url}}/1

###