GET http://localhost:3001/api/sub-trash-bin

###

GET http://localhost:3001/api/sub-trash-bin/id/1

###

GET http://localhost:3001/api/sub-trash-bin/extend

###

GET http://localhost:3001/api/sub-trash-bin/id/2/extend

###

POST http://localhost:3001/api/sub-trash-bin
Content-Type: application/json

{
    "trashBinId": 21,
    "name": "Sub Trash Bin 3"
}

###

PUT http://localhost:3001/api/sub-trash-bin/2
Content-Type: application/json

{
    "name": "Sub Trash Bin 4"
}

###

DELETE http://localhost:3001/api/sub-trash-bin/1

###