@base_url = {{$dotenv URL}}/api
@url={{base_url}}/trash

GET {{url}}

###

GET {{url}}?page=1&count=5

###

GET {{url}}/id/1

###

GET {{url}}/area-chart-total

###

POST {{url}}
Content-Type: application/json

{
    "subTrashBinId": 4
}

###

DELETE {{url}}/1

###